version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Cpx2020@   # senha do root
      MYSQL_DATABASE: CatalogoDb          # cria um banco inicial
    ports:
      - "3306:3306"   # expõe a porta do MySQL
    volumes:
      - db_data:/var/lib/mysql  # volume para persistência dos dados

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "8080:80"   # acessa no navegador em http://localhost:8080
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Cpx2020@
    depends_on:
      - mysql

volumes:
  db_data:
  
  